"""HTML templates for the alexandria wiki generator.

Pure Python string templates. No template engine, no external dependencies
beyond the standard library. Each template is a callable that takes the data
it needs and returns the rendered HTML as a string.

Design constraints:
- No JavaScript in any output
- All navigation via relative links that work over file://
- Dark mode handled by CSS media query, not by template logic
"""

import re
from datetime import date
from html import escape

STYLESHEET_REL = "_assets/style.css"


def _author_sort_key(author: str | None) -> str:
    """Sort key for author: last name of the first author, lowercased.

    Strips parenthetical annotations (e.g., "(edited by ...)"), takes the
    first comma-separated author, and uses its last whitespace-separated
    token. Returns an empty string when no author is provided.
    """
    if not author:
        return ""
    stripped = re.sub(r"\s*\([^)]*\)", "", author).strip()
    first = stripped.split(",", 1)[0].strip()
    parts = first.split()
    return parts[-1].lower() if parts else ""


def _stats_html(library: dict, all_items: list[dict], from_subdir: bool = False) -> str:
    """Compute the footer stats line — item count, section count, form split,
    and a Journal link. Used in the footer of every page."""
    active = [b for b in all_items if b.get("status", "active") != "removed"]
    total = len(active)
    sections = {b.get("section", "unsorted") for b in active}
    n_sections = len(sections)
    form_counts = {"physical": 0, "digital": 0}
    for b in active:
        form = b.get("form", "digital")
        form_counts[form] = form_counts.get(form, 0) + 1
    prefix = "../" if from_subdir else ""
    item_word = "item" if total == 1 else "items"
    section_word = "section" if n_sections == 1 else "sections"
    return (
        f"{total} {item_word} · "
        f"{n_sections} {section_word} · "
        f"{form_counts.get('physical', 0)} physical · "
        f"{form_counts.get('digital', 0)} digital"
        f"&ensp;|&ensp;"
        f'<a href="{prefix}collection-journal/index.html">Journal</a>'
    )


def _page(title: str, body: str, library: dict, all_items: list[dict],
          axes_current: str | None = None, from_subdir: bool = False) -> str:
    """Wrap body content in the full HTML page shell.

    Every page shares the same three rows: header (collection name + search),
    axes nav (with optional highlight for the current view), and footer
    (stats + Journal + credit). Templates pass `axes_current` to highlight
    their axis, or None for pages outside the axes list (search, journal,
    item pages).
    """
    collection_name = library.get("collection_name", "alexandria")
    css_rel = ("../" if from_subdir else "") + STYLESHEET_REL
    search_prefix = "../" if from_subdir else ""
    display_name = escape(collection_name)
    if from_subdir:
        name_html = f'<a href="../index.html" class="header-home">{display_name}</a>'
    else:
        name_html = display_name
    axes_nav_html = _axes_nav(current=axes_current, from_subdir=from_subdir)
    stats = _stats_html(library, all_items, from_subdir=from_subdir)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)}</title>
<link rel="stylesheet" href="{css_rel}">
</head>
<body>
<header class="page-header">
<h1>{name_html}</h1>
<form class="header-search-form" action="{search_prefix}search/index.html" method="get" role="search">
<label for="header-q" class="header-search-icon" aria-label="Search">&#x1F50D;</label>
<input id="header-q" type="text" name="q" placeholder="Search…" autocomplete="off">
</form>
</header>
{axes_nav_html}
<main>
{body}
</main>
<footer class="page-footer">
<div class="footer-stats">{stats}</div>
<div>Generated by alexandria — <a href="https://github.com/msyvr/alexandria">github.com/msyvr/alexandria</a></div>
</footer>
</body>
</html>
"""


def _item_card(item: dict, item_page_rel: str, show_description: bool = True) -> str:
    """Render a single item as a card for an index page."""
    title = escape(item.get("title", "Untitled"))
    description = escape(item.get("description", ""))
    author = item.get("author")
    author_escaped = escape(author) if author else ""
    book_type = escape(item.get("book_type", "unknown"))
    media_type = escape(item.get("media_type", ""))
    date_added = escape(item.get("date_added", ""))
    status = item.get("status", "active")

    author_line = f'<div class="meta">{author_escaped}</div>' if author else ""

    detail_parts = [book_type]
    if media_type:
        detail_parts.append(media_type)
    detail = " · ".join(detail_parts)

    removed_class = " removed" if status == "removed" else ""
    removed_tag = '<span class="removed-tag">removed</span>' if status == "removed" else ""

    description_line = f'<p class="description">{description}</p>' if show_description else ""

    # Data attributes power client-side sort (All view) and filter (By
    # author/artist view). Harmless on other views.
    #   data-author      — sort key: last name of the first author
    #   data-author-full — match target for the author filter (full string, lowercased)
    author_raw = (author or "").lower()
    data_attrs = (
        f' data-date="{date_added}"'
        f' data-author="{escape(_author_sort_key(author))}"'
        f' data-author-full="{escape(author_raw)}"'
        f' data-title="{title.lower()}"'
    )

    return f"""<article class="item-card{removed_class}"{data_attrs}>
<h3><a href="{item_page_rel}">{title}</a>{removed_tag}</h3>
{author_line}
{description_line}
<div class="detail">{detail}</div>
</article>"""


def _axes_nav(current: str | None = None, from_subdir: bool = False) -> str:
    """Navigation bar linking to all index pages.

    `from_subdir`: True when rendering from inside a subdirectory (by-section/,
    all/, etc.) — links need ../ prefix to reach sibling directories.
    False when rendering from the wiki root (homepage).
    """
    axes = [
        ("all", "All"),
        ("by-section", "By section"),
        ("by-author", "By author/artist"),
        ("by-medium-format", "By medium & format"),
        ("by-topic", "Let the LLM decide"),
    ]
    prefix = "../" if from_subdir else ""
    links = []
    for slug, label in axes:
        href = f"{prefix}{slug}/index.html"
        if slug == current:
            links.append(f'<a href="{href}" aria-current="page"><strong>{label}</strong></a>')
        else:
            links.append(f'<a href="{href}">{label}</a>')
    return '<div class="axes-nav">' + "\n".join(links) + "</div>"


def homepage(library: dict, all_items: list[dict]) -> str:
    """Render the wiki homepage."""
    collection_name = library.get("collection_name", "alexandria")
    active = [b for b in all_items if b.get("status", "active") != "removed"]
    recent = sorted(active, key=lambda b: b.get("date_added", ""), reverse=True)[:3]
    if recent:
        recent_cards = "\n".join(
            _item_card(b, f"items/{b['slug']}.html") for b in recent
        )
        body = f"""<h2>Recent additions</h2>
<div class="index-grid">
{recent_cards}
</div>
"""
    else:
        body = """<h2>Recent additions</h2>
<p>No items yet. Use <code>/coll</code> or <code>/coll-physical</code>, <code>/coll-digital</code>, or <code>/coll-scout</code> to add your first item.</p>
"""
    return _page(collection_name, body, library, all_items, axes_current=None, from_subdir=False)


def by_section_index(library: dict, all_items: list[dict], items_by_section: dict[str, list[dict]]) -> str:
    """Render the by-section index: list of sections with counts."""
    rows = []
    for section in sorted(items_by_section.keys()):
        items = [b for b in items_by_section[section] if b.get("status", "active") != "removed"]
        count = len(items)
        section_slug = section.replace("/", "-").replace(" ", "-").lower()
        rows.append(
            f'<tr><td><a href="{section_slug}.html">{escape(section)}</a> ({count})</td></tr>'
        )
    body = '<table><tbody>' + "\n".join(rows) + '</tbody></table>'
    return _page("By section", body, library, all_items, axes_current="by-section", from_subdir=True)


def section_page(section: str, items: list[dict], library: dict, all_items: list[dict]) -> str:
    """Render a single section page: all items in that section."""
    if not items:
        body_main = '<p>No items in this section yet.</p>'
    else:
        cards = "\n".join(_item_card(b, f"../items/{b['slug']}.html") for b in items)
        body_main = f'<div class="index-grid">\n{cards}\n</div>'

    body = f"""<p><a href="index.html">← All sections</a></p>

{body_main}
"""
    return _page(f"Section: {section}", body, library, all_items, axes_current="by-section", from_subdir=True)


def all_index(library: dict, all_items: list[dict]) -> str:
    """Render the All view: flat list of items sorted by date added (newest
    first) by default, with a client-side sort selector."""
    active = [b for b in all_items if b.get("status", "active") != "removed"]
    sorted_items = sorted(active, key=lambda b: b.get("date_added", ""), reverse=True)

    cards = "\n".join(
        _item_card(b, f"../items/{b['slug']}.html", show_description=False)
        for b in sorted_items
    )
    listing = cards if cards else "<p>No items to display.</p>"

    sort_control = """<div class="sort-control">
<label for="sort-select">Sort by</label>
<select id="sort-select">
<option value="date-desc" selected>Date added — newest first</option>
<option value="date-asc">Date added — oldest first</option>
<option value="author-asc">Author / artist</option>
<option value="title-asc">Title</option>
</select>
</div>"""

    sort_script = """<script>
(function() {
  var select = document.getElementById('sort-select');
  var container = document.getElementById('all-listing');
  if (!select || !container) return;
  select.addEventListener('change', function() {
    var value = select.value;
    var items = Array.prototype.slice.call(container.querySelectorAll('.item-card'));
    var key, dir;
    if (value === 'date-desc') { key = 'date'; dir = -1; }
    else if (value === 'date-asc') { key = 'date'; dir = 1; }
    else if (value === 'author-asc') { key = 'author'; dir = 1; }
    else if (value === 'title-asc') { key = 'title'; dir = 1; }
    else return;
    items.sort(function(a, b) {
      var av = a.dataset[key] || '', bv = b.dataset[key] || '';
      if (av < bv) return -1 * dir;
      if (av > bv) return 1 * dir;
      return 0;
    });
    items.forEach(function(el) { container.appendChild(el); });
  });
})();
</script>"""

    body = f"""{sort_control}

<div id="all-listing" class="index-grid">
{listing}
</div>

{sort_script}
"""
    return _page("All", body, library, all_items, axes_current="all", from_subdir=True)


def by_author_index(library: dict, all_items: list[dict]) -> str:
    """Render the By author/artist view: items sorted by author last name,
    with a live filter input at the top."""
    active = [b for b in all_items if b.get("status", "active") != "removed"]
    # Items without an author sort to the very end via the \uffff sentinel;
    # secondary sort is by title within the same last-name key.
    sorted_items = sorted(
        active,
        key=lambda b: (
            _author_sort_key(b.get("author")) or "\uffff",
            b.get("title", "").lower(),
        ),
    )
    cards = "\n".join(
        _item_card(b, f"../items/{b['slug']}.html", show_description=False)
        for b in sorted_items
    )
    listing = cards if cards else "<p>No items to display.</p>"

    filter_script = """<script>
(function() {
  var input = document.getElementById('author-filter-input');
  var container = document.getElementById('by-author-listing');
  if (!input || !container) return;
  var cards = container.querySelectorAll('.item-card');
  input.addEventListener('input', function() {
    var q = input.value.trim().toLowerCase();
    cards.forEach(function(el) {
      if (!q) { el.style.display = ''; return; }
      var name = el.dataset.authorFull || '';
      el.style.display = (name.indexOf(q) !== -1) ? '' : 'none';
    });
  });
})();
</script>"""

    body = f"""<form class="search-form" role="search" onsubmit="return false;">
<input type="text" id="author-filter-input" placeholder="Filter by author/artist — type to narrow, clear to see all" autocomplete="off">
</form>

<div id="by-author-listing" class="index-grid">
{listing}
</div>

{filter_script}
"""
    return _page("By author/artist", body, library, all_items, axes_current="by-author", from_subdir=True)


def _format_slug(form: str, fmt: str) -> str:
    """URL-safe slug for a (form, media_type) pair: e.g. 'physical-text-hardcover'."""
    return f"{form}-{fmt}".replace(":", "-").replace("/", "-").replace(" ", "-").lower()


def by_medium_format_index(library: dict, all_items: list[dict]) -> str:
    """Render the by-medium-format index: two tables (Physical, Digital),
    each listing media_type values with active-item counts.
    """
    form_groups: dict[str, dict[str, list[dict]]] = {"physical": {}, "digital": {}}
    for item in all_items:
        form = item.get("form", "digital")
        media_type = item.get("media_type", "unknown") or "unknown"
        form_groups.setdefault(form, {}).setdefault(media_type, []).append(item)

    sections = []
    for form in ["physical", "digital"]:
        formats = form_groups.get(form, {})
        active_total = sum(
            len([b for b in items if b.get("status", "active") != "removed"])
            for items in formats.values()
        )
        if active_total == 0:
            continue
        rows = []
        for fmt in sorted(formats.keys()):
            count = len([b for b in formats[fmt] if b.get("status", "active") != "removed"])
            if count == 0:
                continue
            slug = _format_slug(form, fmt)
            rows.append(
                f'<tr><td><a href="{slug}.html">{escape(fmt)}</a> ({count})</td></tr>'
            )
        if not rows:
            continue
        table = '<table><tbody>' + "\n".join(rows) + '</tbody></table>'
        sections.append(
            f'<div class="section-group"><h2>{escape(form.capitalize())} '
            f'<small>({active_total})</small></h2>\n{table}</div>'
        )

    body = ''.join(sections) if sections else '<p>No items to display.</p>'
    return _page("By medium & format", body, library, all_items, axes_current="by-medium-format", from_subdir=True)


def format_page(form: str, fmt: str, items: list[dict], library: dict, all_items: list[dict]) -> str:
    """Render a single (form, media_type) page: all items matching that pair."""
    if not items:
        body_main = '<p>No items in this format yet.</p>'
    else:
        cards = "\n".join(_item_card(b, f"../items/{b['slug']}.html") for b in items)
        body_main = f'<div class="index-grid">\n{cards}\n</div>'

    body = f"""<p><a href="index.html">← All formats</a></p>

{body_main}
"""
    title = f"{form.capitalize()}: {fmt}"
    return _page(title, body, library, all_items, axes_current="by-medium-format", from_subdir=True)


def topic_placeholder(library: dict, all_items: list[dict]) -> str:
    """Pass 2 scaffolding: placeholder for the topic index page."""
    body = """<p>Topic pages will appear here once narrative layer generation is enabled.</p>

<p>The narrative layer uses an LLM to extract topics from your items and generate
cross-references between them. It's an optional enhancement — the wiki works fully
without it.</p>
"""
    return _page("Let the LLM decide", body, library, all_items, axes_current="by-topic", from_subdir=True)


def _journal_entry_html(entry: dict, show_detail: bool = True) -> str:
    """Render a single journal entry as an <article> card.

    `show_detail`: when False, omits the full_html body — useful for the
    landing page where only date + headline are shown.
    """
    date = escape(entry.get("date", ""))
    time = escape(entry.get("time", ""))
    accomplished = escape(entry.get("accomplished", ""))
    full_html = entry.get("full_html", "")
    timestamp = date + (f" at {time}" if time else "")
    headline = accomplished if accomplished else "Checkpoint"
    detail_block = f'<div class="journal-detail">\n{full_html}\n</div>' if show_detail else ""
    entry_class = "journal-entry" if show_detail else "journal-entry journal-entry-compact"
    return f"""<article class="{entry_class}">
<div class="journal-date">{timestamp}</div>
<h3 class="journal-headline">{headline}</h3>
{detail_block}
</article>"""


def _group_entries_by_month(entries: list[dict]) -> dict[str, list[dict]]:
    """Group entries by YYYY-MM (or "undated" if date is too short)."""
    months: dict[str, list[dict]] = {}
    for entry in entries:
        date = entry.get("date", "")
        month_key = date[:7] if len(date) >= 7 else "undated"
        months.setdefault(month_key, []).append(entry)
    return months


def collection_journal(library: dict, all_items: list[dict], entries: list[dict]) -> str:
    """Render the journal landing: the 3 most recent entries, then a table
    of months linking to per-month pages."""
    if not entries:
        body = """<p>No journal entries yet. After adding items or making changes to your collection,
run <code>/coll-notes</code> to record what was done. You can also add personal
notes about your collection — thoughts, plans, or anything you want to remember.</p>

<p>Journal entries appear here as a timeline, grouped by month.</p>
"""
        return _page("Journal", body, library, all_items, axes_current=None, from_subdir=True)

    sorted_entries = sorted(
        entries,
        key=lambda e: e.get("date", "") + e.get("time", ""),
        reverse=True,
    )
    recent_html = "\n".join(_journal_entry_html(e, show_detail=False) for e in sorted_entries[:3])

    months = _group_entries_by_month(entries)
    rows = []
    for month_key in sorted(months.keys(), reverse=True):
        label = escape(month_key) if month_key != "undated" else "Undated"
        rows.append(f'<tr><td><a href="{month_key}.html">{label}</a></td></tr>')
    months_table = (
        '<table><thead><tr><th>Month</th></tr></thead><tbody>'
        + "\n".join(rows)
        + "</tbody></table>"
    )

    body = f"""<p class="journal-intro">A timeline of your collection — what was added, changed, and decided,
in chronological order. Run <code>/coll-notes</code> to add entries with personal details.</p>

<h2>Recent</h2>
{recent_html}

<h2>Browse by month</h2>
{months_table}
"""
    return _page("Journal", body, library, all_items, axes_current=None, from_subdir=True)


def collection_journal_month(library: dict, all_items: list[dict], month_key: str, month_entries: list[dict]) -> str:
    """Render a single-month journal page: all entries for that month."""
    sorted_entries = sorted(
        month_entries,
        key=lambda e: e.get("date", "") + e.get("time", ""),
        reverse=True,
    )
    entries_html = "\n".join(_journal_entry_html(e) for e in sorted_entries)
    label = escape(month_key) if month_key != "undated" else "Undated"
    body = f"""<p><a href="index.html">← All months</a></p>

<h2>{label}</h2>
{entries_html}
"""
    return _page(f"Journal: {label}", body, library, all_items, axes_current=None, from_subdir=True)


def search_page(library: dict, all_items: list[dict]) -> str:
    """Render the search page with inline JS for filtering and highlighting.

    Fully client-side: no external dependencies, no CDN, no network requests.
    The JS filters items to show only matches and highlights matching text.
    Case-insensitive partial matching. Works over file://.
    """
    # Build the flat listing — every active item with all searchable fields visible
    item_entries = []
    active = [b for b in all_items if b.get("status", "active") != "removed"]
    for item in sorted(active, key=lambda b: b.get("title", "").lower()):
        title = escape(item.get("title", "Untitled"))
        author = escape(item.get("author", ""))
        description = escape(item.get("description", ""))
        section = escape(item.get("section", ""))
        media_type = escape(item.get("media_type", ""))
        slug = item.get("slug", "")
        user_notes = escape(item.get("user_notes", ""))

        parts = [f'<div class="search-item" data-searchable>']
        parts.append(f'<div class="search-title"><a href="../items/{slug}.html">{title}</a></div>')
        if author:
            parts.append(f'<div class="search-meta">{author}</div>')
        if description:
            parts.append(f'<div class="search-desc">{description}</div>')
        detail_parts = []
        if section:
            detail_parts.append(section)
        if media_type:
            detail_parts.append(media_type)
        if detail_parts:
            parts.append(f'<div class="search-detail">{" · ".join(detail_parts)}</div>')
        if user_notes:
            parts.append(f'<div class="search-notes">{user_notes}</div>')
        parts.append('</div>')
        item_entries.append("\n".join(parts))

    listing = "\n".join(item_entries) if item_entries else "<p>No items in the collection yet.</p>"

    # The search script: ~80 lines inline, zero dependencies
    search_script = """
<script>
(function() {
  var input = document.getElementById('search-input');
  var prompt = document.getElementById('search-prompt');
  var items = document.querySelectorAll('[data-searchable]');
  var listing = document.querySelector('.search-listing');

  // Read query from URL on page load
  var params = new URLSearchParams(location.search);
  var initial = params.get('q') || '';
  if (initial) {
    input.value = initial;
    runSearch(initial);
  }

  // Live search on input (no need to press Enter after first load)
  input.addEventListener('input', function() {
    runSearch(input.value);
  });

  // Prevent form submission reload when typing — search live instead
  input.closest('form').addEventListener('submit', function(e) {
    e.preventDefault();
    runSearch(input.value);
    // Update URL without reload so bookmarking works
    var url = new URL(location);
    if (input.value) url.searchParams.set('q', input.value);
    else url.searchParams.delete('q');
    history.replaceState(null, '', url);
  });

  function runSearch(query) {
    var q = query.trim().toLowerCase();

    // Clear previous highlights
    items.forEach(function(el) {
      el.style.display = '';
      // Restore original text (strip <mark> tags)
      el.querySelectorAll('mark').forEach(function(m) {
        m.replaceWith(m.textContent);
      });
    });

    if (!q) {
      prompt.style.display = 'none';
      return;
    }

    var shown = 0;
    var terms = q.split(/\\s+/).filter(function(t) { return t.length > 0; });

    items.forEach(function(el) {
      var text = el.textContent.toLowerCase();
      var match = terms.every(function(t) { return text.indexOf(t) !== -1; });

      if (match) {
        el.style.display = '';
        shown++;
        // Highlight matching terms in text nodes
        highlightTerms(el, terms);
      } else {
        el.style.display = 'none';
      }
    });

    prompt.style.display = 'block';
    if (shown === 0) {
      prompt.innerHTML = 'No matches for <strong>' + esc(query) + '</strong>';
    } else {
      prompt.innerHTML = shown + ' match' + (shown === 1 ? '' : 'es') + ' for <strong>' + esc(query) + '</strong>';
    }
  }

  function highlightTerms(root, terms) {
    var walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null);
    var nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);

    nodes.forEach(function(node) {
      var html = node.textContent;
      terms.forEach(function(term) {
        var re = new RegExp('(' + escRegex(term) + ')', 'gi');
        html = html.replace(re, '<mark>$1</mark>');
      });
      if (html !== node.textContent) {
        var span = document.createElement('span');
        span.innerHTML = html;
        node.replaceWith(span);
      }
    });
  }

  function esc(s) { return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
  function escRegex(s) { return s.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&'); }
})();
</script>"""

    body = f"""<form class="search-form" action="index.html" method="get">
<input type="text" name="q" placeholder="Search the collection…" id="search-input" autocomplete="off">
</form>

<div id="search-prompt" class="search-prompt" style="display:none;"></div>

<div class="search-listing">
{listing}
</div>

{search_script}
"""
    return _page("Search", body, library, all_items, axes_current=None, from_subdir=True)


def item_page(item: dict, readme_html: str, readme_truncated: bool, library: dict, all_items: list[dict], item_notes: list[dict] | None = None) -> str:
    """Render a single item page.

    `readme_html` is the item's README content rendered to HTML (may be empty).
    `readme_truncated` is True if the content was truncated to the word limit.
    `item_notes` is a list of note dicts from the notes/ directory, each with:
      filename, title, html, is_pdf.
    """
    title = escape(item.get("title", "Untitled"))
    description = escape(item.get("description", ""))
    author = item.get("author")
    user_notes = item.get("user_notes")
    book_type = escape(item.get("book_type", "unknown"))
    form = escape(item.get("form", ""))
    media_type = escape(item.get("media_type", ""))
    section = escape(item.get("section", ""))
    date_added = escape(item.get("date_added", ""))
    status = item.get("status", "active")
    settled = bool(item.get("settled", False))
    slug = escape(item.get("slug", ""))
    path = item.get("path", "")

    # Metadata grid
    metadata_rows = []
    if media_type:
        metadata_rows.append(f"<dt>Format</dt><dd>{media_type} ({form})</dd>")
    else:
        metadata_rows.append(f"<dt>Form</dt><dd>{form}</dd>")
    metadata_rows.append(f"<dt>Section</dt><dd><a href=\"../by-section/{section.lower().replace(' ', '-')}.html\">{section}</a></dd>")
    metadata_rows.append(f"<dt>Added</dt><dd>{date_added}</dd>")

    if item.get("book_type") == "scout":
        if settled:
            settled_at = escape(item.get("settled_at", ""))
            metadata_rows.append(f"<dt>Status</dt><dd>Settled{' ' + settled_at if settled_at else ''}</dd>")
        else:
            metadata_rows.append(f"<dt>Status</dt><dd>Live scout</dd>")

    if status == "removed":
        removed_at = escape(item.get("removed_at", ""))
        removed_reason = escape(item.get("removed_reason", ""))
        metadata_rows.append(f"<dt>Status</dt><dd><strong>Removed</strong>{' ' + removed_at if removed_at else ''}</dd>")
        if removed_reason:
            metadata_rows.append(f"<dt>Reason</dt><dd>{removed_reason}</dd>")

    metadata_block = f'<div class="item-metadata"><dl>{"".join(metadata_rows)}</dl></div>'

    # Thumbnail: use the original for image items, else a `photo` field (physical
    # items sometimes preserve a cover photo). Wrapped in a flex row with the
    # metadata grid so the two sit side-by-side; the header-row itself renders
    # even without a thumbnail, keeping the metadata at 50% width.
    provenance = item.get("provenance", {}) if isinstance(item.get("provenance"), dict) else {}
    original_path_field = provenance.get("original_path", "")
    thumb_src = ""
    raw_media_type = item.get("media_type", "") or ""
    if path and status != "removed":
        if raw_media_type.startswith("image:") and original_path_field:
            thumb_src = f"../../{path}/{original_path_field}"
        elif item.get("photo"):
            thumb_src = f"../../{path}/{escape(item.get('photo'))}"
    thumb_html = (
        f'<img class="item-thumb" src="{thumb_src}" alt="{title}">'
        if thumb_src else ""
    )
    header_row = f'<div class="item-header-row">{metadata_block}{thumb_html}</div>'

    # File link for digital items with original files
    file_link = ""
    if form == "digital" and status != "removed" and item.get("book_type") != "scout":
        if original_path_field:
            file_link = f'<p class="file-link">Open <a href="../../{path}/{original_path_field}">{escape(original_path_field)}</a> from the <a href="../../{path}/">item directory</a></p>'
        else:
            file_link = f'<p class="file-link"><a href="../../{path}/">Browse item directory</a></p>'

    # Content block
    if status == "removed":
        content_block = """<div class="removed-notice">
<strong>Resource removed.</strong> This item is kept in the catalog as a historical
record. The original content is no longer in the collection.
</div>"""
    elif item.get("book_type") == "scout" and not settled:
        # Live scout: thin catalog entry linking to the scout's own presentation
        content_block = f"""<div class="item-content">
<p><a href="../../{path}/README.md">Open the scout's full content</a> in a markdown viewer,
or <a href="../../{path}/">browse the scout directory</a>.</p>
</div>"""
    elif readme_html:
        truncation_note = ""
        if readme_truncated:
            truncation_note = f'<p><em>Content truncated. <a href="../../{path}/README.md">See full README</a>.</em></p>'
        content_block = f'<div class="item-content">\n{readme_html}\n{truncation_note}\n</div>'
    else:
        content_block = f"""<div class="item-content">
<p>Content is preserved in the item's directory. <a href="../../{path}/">Browse the item directory</a>.</p>
</div>"""

    description_html = f'<p class="description">{description}</p>' if description else ""
    user_notes_html = f'<blockquote class="user-notes"><p>{escape(user_notes)}</p></blockquote>' if user_notes else ""

    # Render notes from notes/ directory
    notes_section = ""
    if item_notes:
        note_blocks = []
        for note in (item_notes or []):
            if note["is_pdf"]:
                note_blocks.append(
                    f'<div class="note-entry">'
                    f'<h3>{escape(note["title"])}</h3>'
                    f'<p>📄 <a href="../../{path}/notes/{note["filename"]}">Open as PDF</a></p>'
                    f'</div>'
                )
            else:
                note_blocks.append(
                    f'<div class="note-entry">'
                    f'<h3>{escape(note["title"])}</h3>'
                    f'{note["html"]}'
                    f'</div>'
                )
        notes_section = f"""<div class="item-notes">
<h2>Notes</h2>
{''.join(note_blocks)}
</div>"""

    metadata_link = ""
    if status != "removed" and path:
        metadata_link = (
            f'<p class="file-link">Open <a href="../../{path}/metadata.yaml">metadata.yaml</a> '
            f'from the <a href="../../{path}/">item directory</a></p>'
        )

    body = f"""<p><a href="../index.html" onclick="if (history.length &gt; 1) {{ history.back(); return false; }}">← Back</a></p>

{description_html}

{user_notes_html}

{header_row}

{file_link}

{content_block}

{notes_section}

{metadata_link}
"""

    return _page(title, body, library, all_items, axes_current=None, from_subdir=True)
