"""HTML templates for the alexandria wiki generator.

Pure Python string templates. No template engine, no external dependencies
beyond the standard library. Each template is a callable that takes the data
it needs and returns the rendered HTML as a string.

Design constraints:
- No JavaScript in any output
- All navigation via relative links that work over file://
- Dark mode handled by CSS media query, not by template logic
"""

from datetime import date
from html import escape

STYLESHEET_REL = "_assets/style.css"


def _page(title: str, breadcrumb_html: str, body: str, css_rel: str = STYLESHEET_REL) -> str:
    """Wrap body content in the full HTML page shell."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)}</title>
<link rel="stylesheet" href="{css_rel}">
</head>
<body>
<nav class="breadcrumb">{breadcrumb_html}</nav>
<header class="page-header">
<h1>{escape(title)}</h1>
</header>
<main>
{body}
</main>
<footer class="page-footer">
Generated by alexandria — <a href="https://github.com/msyvr/alexandria">github.com/msyvr/alexandria</a>
</footer>
</body>
</html>
"""


def _book_card(book: dict, book_page_rel: str) -> str:
    """Render a single book as a card for an index page."""
    title = escape(book.get("title", "Untitled"))
    description = escape(book.get("description", ""))
    author = book.get("author")
    book_type = escape(book.get("book_type", "unknown"))
    media_type = escape(book.get("media_type", ""))
    status = book.get("status", "active")

    meta_parts = []
    if author:
        meta_parts.append(escape(author))
    meta_parts.append(book_type)
    if media_type:
        meta_parts.append(media_type)
    meta = " · ".join(meta_parts)

    removed_class = " removed" if status == "removed" else ""
    removed_tag = '<span class="removed-tag">removed</span>' if status == "removed" else ""

    return f"""<article class="book-card{removed_class}">
<h3><a href="{book_page_rel}">{title}</a>{removed_tag}</h3>
<div class="meta">{meta}</div>
<p class="description">{description}</p>
</article>"""


def _axes_nav(current: str | None = None) -> str:
    """Navigation bar linking to all index pages."""
    axes = [
        ("by-section", "By section"),
        ("by-date", "By date"),
        ("by-type", "By type"),
        ("by-form", "By form"),
        ("by-media-type", "By media type"),
        ("by-topic", "By topic"),
    ]
    links = []
    for slug, label in axes:
        if slug == current:
            links.append(f'<a href="{slug}/index.html" aria-current="page"><strong>{label}</strong></a>')
        else:
            links.append(f'<a href="{slug}/index.html">{label}</a>')
    return '<div class="axes-nav">' + "\n".join(links) + "</div>"


def homepage(library: dict, all_books: list[dict]) -> str:
    """Render the wiki homepage."""
    library_name = library.get("library_name", "alexandria")
    total = len([b for b in all_books if b.get("status", "active") != "removed"])

    section_counts: dict[str, int] = {}
    type_counts: dict[str, int] = {}
    form_counts: dict[str, int] = {"physical": 0, "digital": 0}
    for book in all_books:
        if book.get("status", "active") == "removed":
            continue
        section_counts[book.get("section", "unsorted")] = section_counts.get(book.get("section", "unsorted"), 0) + 1
        type_counts[book.get("book_type", "unknown")] = type_counts.get(book.get("book_type", "unknown"), 0) + 1
        form_counts[book.get("form", "digital")] = form_counts.get(book.get("form", "digital"), 0) + 1

    n_sections = len(section_counts)
    n_types = len(type_counts)

    # Recent additions (most recent 10, excluding removed)
    active = [b for b in all_books if b.get("status", "active") != "removed"]
    recent = sorted(active, key=lambda b: b.get("date_added", ""), reverse=True)[:10]
    if recent:
        recent_cards = "\n".join(
            _book_card(b, f"books/{b['slug']}.html") for b in recent
        )
        recent_section = f"""<h2>Recent additions</h2>
<div class="index-grid">
{recent_cards}
</div>"""
    else:
        recent_section = """<h2>Recent additions</h2>
<p>No books yet. Use <code>/library</code> or <code>/new-physical</code>, <code>/new-digital</code>, or <code>/new-scout</code> to add your first book.</p>"""

    body = f"""<p class="library-intro">
Welcome to <strong>{escape(library_name)}</strong> — your personal curated library.
</p>

<div class="summary">
<span class="stat"><strong>{total}</strong> book{'s' if total != 1 else ''}</span>
<span class="stat"><strong>{n_sections}</strong> section{'s' if n_sections != 1 else ''}</span>
<span class="stat"><strong>{form_counts.get('physical', 0)}</strong> physical</span>
<span class="stat"><strong>{form_counts.get('digital', 0)}</strong> digital</span>
</div>

<h2>Browse</h2>
{_axes_nav()}

{recent_section}
"""
    return _page(library_name, '<a href="index.html">Home</a>', body, STYLESHEET_REL)


def by_section_index(library: dict, books_by_section: dict[str, list[dict]]) -> str:
    """Render the by-section index: list of sections with counts."""
    library_name = library.get("library_name", "alexandria")
    rows = []
    for section in sorted(books_by_section.keys()):
        books = [b for b in books_by_section[section] if b.get("status", "active") != "removed"]
        count = len(books)
        # Section filename is the section name itself, safe-ified by the generator
        section_slug = section.replace("/", "-").replace(" ", "-").lower()
        rows.append(
            f'<tr><td><a href="{section_slug}.html">{escape(section)}</a></td><td>{count}</td></tr>'
        )
    table = (
        '<table><thead><tr><th>Section</th><th>Books</th></tr></thead><tbody>'
        + "\n".join(rows)
        + "</tbody></table>"
    )

    body = f"""{_axes_nav("by-section")}

{table}
"""
    breadcrumb = '<a href="../index.html">Home</a> / By section'
    return _page(f"{library_name} — by section", breadcrumb, body, "../" + STYLESHEET_REL)


def section_page(section: str, books: list[dict]) -> str:
    """Render a single section page: all books in that section."""
    if not books:
        body_main = '<p>No books in this section yet.</p>'
    else:
        cards = "\n".join(_book_card(b, f"../books/{b['slug']}.html") for b in books)
        body_main = f'<div class="index-grid">\n{cards}\n</div>'

    body = f"""<p><a href="index.html">← All sections</a></p>

{body_main}
"""
    breadcrumb = '<a href="../index.html">Home</a> / <a href="index.html">By section</a> / ' + escape(section)
    return _page(f"Section: {section}", breadcrumb, body, "../" + STYLESHEET_REL)


def by_date_index(library: dict, all_books: list[dict]) -> str:
    """Render the by-date index: books newest first, grouped by year-month."""
    library_name = library.get("library_name", "alexandria")
    # Group by YYYY-MM
    groups: dict[str, list[dict]] = {}
    for book in all_books:
        date_added = book.get("date_added", "")
        if not date_added or len(date_added) < 7:
            group_key = "unknown"
        else:
            group_key = date_added[:7]
        groups.setdefault(group_key, []).append(book)

    sections = []
    for group_key in sorted(groups.keys(), reverse=True):
        books = sorted(groups[group_key], key=lambda b: b.get("date_added", ""), reverse=True)
        cards = "\n".join(_book_card(b, f"../books/{b['slug']}.html") for b in books)
        label = escape(group_key) if group_key != "unknown" else "Date unknown"
        sections.append(
            f'<div class="section-group"><h2>{label}</h2><div class="index-grid">\n{cards}\n</div></div>'
        )

    body = f"""{_axes_nav("by-date")}

{''.join(sections) if sections else '<p>No books to display.</p>'}
"""
    breadcrumb = '<a href="../index.html">Home</a> / By date'
    return _page(f"{library_name} — by date", breadcrumb, body, "../" + STYLESHEET_REL)


def by_type_index(library: dict, all_books: list[dict]) -> str:
    """Render the by-type index: books grouped by book_type."""
    library_name = library.get("library_name", "alexandria")
    groups: dict[str, list[dict]] = {}
    for book in all_books:
        groups.setdefault(book.get("book_type", "unknown"), []).append(book)

    sections = []
    for type_name in sorted(groups.keys()):
        books = sorted(groups[type_name], key=lambda b: b.get("title", "").lower())
        cards = "\n".join(_book_card(b, f"../books/{b['slug']}.html") for b in books)
        count = len([b for b in books if b.get("status", "active") != "removed"])
        sections.append(
            f'<div class="section-group"><h2>{escape(type_name)} <small>({count})</small></h2>'
            f'<div class="index-grid">\n{cards}\n</div></div>'
        )

    body = f"""{_axes_nav("by-type")}

{''.join(sections) if sections else '<p>No books to display.</p>'}
"""
    breadcrumb = '<a href="../index.html">Home</a> / By type'
    return _page(f"{library_name} — by type", breadcrumb, body, "../" + STYLESHEET_REL)


def by_form_index(library: dict, all_books: list[dict]) -> str:
    """Render the by-form index: physical vs digital."""
    library_name = library.get("library_name", "alexandria")
    groups: dict[str, list[dict]] = {"physical": [], "digital": []}
    for book in all_books:
        form = book.get("form", "digital")
        groups.setdefault(form, []).append(book)

    sections = []
    for form_name in ["physical", "digital"]:
        books = sorted(groups.get(form_name, []), key=lambda b: b.get("title", "").lower())
        cards = "\n".join(_book_card(b, f"../books/{b['slug']}.html") for b in books)
        count = len([b for b in books if b.get("status", "active") != "removed"])
        if count == 0:
            continue
        sections.append(
            f'<div class="section-group"><h2>{form_name.capitalize()} <small>({count})</small></h2>'
            f'<div class="index-grid">\n{cards}\n</div></div>'
        )

    body = f"""{_axes_nav("by-form")}

{''.join(sections) if sections else '<p>No books to display.</p>'}
"""
    breadcrumb = '<a href="../index.html">Home</a> / By form'
    return _page(f"{library_name} — by form", breadcrumb, body, "../" + STYLESHEET_REL)


def by_media_type_index(library: dict, all_books: list[dict]) -> str:
    """Render the by-media-type index: grouped by content_type then format."""
    library_name = library.get("library_name", "alexandria")
    # Two-level grouping: content_type -> format -> [books]
    content_groups: dict[str, dict[str, list[dict]]] = {}
    for book in all_books:
        media_type = book.get("media_type", "")
        if ":" in media_type:
            content_type, fmt = media_type.split(":", 1)
        else:
            content_type, fmt = "other", media_type or "unknown"
        content_groups.setdefault(content_type, {}).setdefault(fmt, []).append(book)

    sections = []
    for content_type in sorted(content_groups.keys()):
        format_groups = content_groups[content_type]
        total_for_type = sum(
            len([b for b in books if b.get("status", "active") != "removed"])
            for books in format_groups.values()
        )
        if total_for_type == 0:
            continue
        format_sections = []
        for fmt in sorted(format_groups.keys()):
            books = sorted(format_groups[fmt], key=lambda b: b.get("title", "").lower())
            cards = "\n".join(_book_card(b, f"../books/{b['slug']}.html") for b in books)
            active_count = len([b for b in books if b.get("status", "active") != "removed"])
            if active_count == 0:
                continue
            format_sections.append(
                f'<h3>{escape(fmt)} <small>({active_count})</small></h3>'
                f'<div class="index-grid">\n{cards}\n</div>'
            )
        sections.append(
            f'<div class="section-group"><h2>{escape(content_type)}</h2>'
            + "\n".join(format_sections)
            + "</div>"
        )

    body = f"""{_axes_nav("by-media-type")}

{''.join(sections) if sections else '<p>No books to display.</p>'}
"""
    breadcrumb = '<a href="../index.html">Home</a> / By media type'
    return _page(f"{library_name} — by media type", breadcrumb, body, "../" + STYLESHEET_REL)


def topic_placeholder(library: dict) -> str:
    """Pass 2 scaffolding: placeholder for the topic index page."""
    library_name = library.get("library_name", "alexandria")
    body = """<p>Topic pages will appear here once narrative layer generation is enabled.</p>

<p>The narrative layer uses an LLM to extract topics from your books and generate
cross-references between them. It's an optional enhancement — the wiki works fully
without it.</p>

<p><a href="../index.html">← Back to home</a></p>
"""
    breadcrumb = '<a href="../index.html">Home</a> / By topic'
    return _page(f"{library_name} — by topic", breadcrumb, body, "../" + STYLESHEET_REL)


def book_page(book: dict, readme_html: str, readme_truncated: bool) -> str:
    """Render a single book page.

    `readme_html` is the book's README content rendered to HTML (may be empty).
    `readme_truncated` is True if the content was truncated to the word limit.
    """
    title = escape(book.get("title", "Untitled"))
    description = escape(book.get("description", ""))
    author = book.get("author")
    book_type = escape(book.get("book_type", "unknown"))
    form = escape(book.get("form", ""))
    media_type = escape(book.get("media_type", ""))
    section = escape(book.get("section", ""))
    date_added = escape(book.get("date_added", ""))
    status = book.get("status", "active")
    settled = bool(book.get("settled", False))
    slug = escape(book.get("slug", ""))
    path = book.get("path", "")

    # Metadata block
    metadata_rows = [
        f"<dt>Book type</dt><dd>{book_type}</dd>",
        f"<dt>Form</dt><dd>{form}</dd>",
    ]
    if media_type:
        metadata_rows.append(f"<dt>Media type</dt><dd>{media_type}</dd>")
    metadata_rows.append(f"<dt>Section</dt><dd><a href=\"../by-section/{section.lower().replace(' ', '-')}.html\">{section}</a></dd>")
    metadata_rows.append(f"<dt>Date added</dt><dd>{date_added}</dd>")
    if author:
        metadata_rows.insert(0, f"<dt>Author</dt><dd>{escape(author)}</dd>")

    if book.get("book_type") == "scout":
        if settled:
            settled_at = escape(book.get("settled_at", ""))
            metadata_rows.append(f"<dt>Scout status</dt><dd>Settled (static reference)</dd>")
            if settled_at:
                metadata_rows.append(f"<dt>Settled at</dt><dd>{settled_at}</dd>")
        else:
            metadata_rows.append(f"<dt>Scout status</dt><dd>Live (updates via discovery)</dd>")

    if status == "removed":
        removed_at = escape(book.get("removed_at", ""))
        removed_reason = escape(book.get("removed_reason", ""))
        metadata_rows.append(f"<dt>Status</dt><dd><strong>Removed</strong></dd>")
        if removed_at:
            metadata_rows.append(f"<dt>Removed at</dt><dd>{removed_at}</dd>")
        if removed_reason:
            metadata_rows.append(f"<dt>Removal reason</dt><dd>{removed_reason}</dd>")

    metadata_block = f"""<div class="book-metadata"><dl>
{''.join(metadata_rows)}
</dl></div>"""

    # Content block
    if status == "removed":
        content_block = """<div class="removed-notice">
<strong>Resource removed.</strong> This book is kept in the catalog as a historical
record. The original content is no longer in the library.
</div>"""
    elif book.get("book_type") == "scout" and not settled:
        # Live scout: thin catalog entry linking to the scout's own presentation
        content_block = f"""<div class="book-content">
<p><a href="../../{path}/README.md">Open the scout's full content</a> in a markdown viewer,
or <a href="../../{path}/">browse the scout directory</a>.</p>
</div>"""
    elif readme_html:
        truncation_note = ""
        if readme_truncated:
            truncation_note = f'<p><em>Content truncated. <a href="../../{path}/README.md">See full README</a>.</em></p>'
        content_block = f'<div class="book-content">\n{readme_html}\n{truncation_note}\n</div>'
    else:
        content_block = f"""<div class="book-content">
<p>Content is preserved in the book's directory. <a href="../../{path}/">Browse the book directory</a>.</p>
</div>"""

    description_html = f'<p class="description">{description}</p>' if description else ""

    body = f"""{description_html}

{metadata_block}

{content_block}

<p><a href="../index.html">← Back to library</a></p>
"""

    breadcrumb = f'<a href="../index.html">Home</a> / <a href="../by-section/{section.lower().replace(" ", "-")}.html">{section}</a> / {title}'
    return _page(title, breadcrumb, body, "../" + STYLESHEET_REL)
