"""HTML templates for the alexandria wiki generator.

Pure Python string templates. No template engine, no external dependencies
beyond the standard library. Each template is a callable that takes the data
it needs and returns the rendered HTML as a string.

Design constraints:
- No JavaScript in any output
- All navigation via relative links that work over file://
- Dark mode handled by CSS media query, not by template logic
"""

from datetime import date
from html import escape

STYLESHEET_REL = "_assets/style.css"


def _page(title: str, breadcrumb_html: str, body: str, css_rel: str = STYLESHEET_REL, stats: str = "", from_subdir: bool = False) -> str:
    """Wrap body content in the full HTML page shell."""
    breadcrumb_block = f'<nav class="breadcrumb">{breadcrumb_html}</nav>' if breadcrumb_html else ""
    stats_line = f'<div class="footer-stats">{stats}</div>' if stats else ""
    search_prefix = "../" if from_subdir else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)}</title>
<link rel="stylesheet" href="{css_rel}">
</head>
<body>
{breadcrumb_block}
<header class="page-header">
<h1>{escape(title)}</h1>
<a href="{search_prefix}search/index.html" class="header-search">Search</a>
</header>
<main>
{body}
</main>
<footer class="page-footer">
{stats_line}
<div>Generated by alexandria — <a href="https://github.com/msyvr/alexandria">github.com/msyvr/alexandria</a></div>
</footer>
</body>
</html>
"""


def _item_card(item: dict, item_page_rel: str) -> str:
    """Render a single item as a card for an index page."""
    title = escape(item.get("title", "Untitled"))
    description = escape(item.get("description", ""))
    author = item.get("author")
    book_type = escape(item.get("book_type", "unknown"))
    media_type = escape(item.get("media_type", ""))
    status = item.get("status", "active")

    author_line = f'<div class="meta">{escape(author)}</div>' if author else ""

    detail_parts = [book_type]
    if media_type:
        detail_parts.append(media_type)
    detail = " · ".join(detail_parts)

    removed_class = " removed" if status == "removed" else ""
    removed_tag = '<span class="removed-tag">removed</span>' if status == "removed" else ""

    return f"""<article class="item-card{removed_class}">
<h3><a href="{item_page_rel}">{title}</a>{removed_tag}</h3>
{author_line}
<p class="description">{description}</p>
<div class="detail">{detail}</div>
</article>"""


def _axes_nav(current: str | None = None, from_subdir: bool = False) -> str:
    """Navigation bar linking to all index pages.

    `from_subdir`: True when rendering from inside a subdirectory (by-section/,
    by-date/, etc.) — links need ../ prefix to reach sibling directories.
    False when rendering from the wiki root (homepage).
    """
    axes = [
        ("by-section", "By section"),
        ("by-date", "By date"),
        ("by-type", "By type"),
        ("by-media-type", "By media type"),
        ("by-topic", "By topic"),
    ]
    prefix = "../" if from_subdir else ""
    links = []
    for slug, label in axes:
        href = f"{prefix}{slug}/index.html"
        if slug == current:
            links.append(f'<a href="{href}" aria-current="page"><strong>{label}</strong></a>')
        else:
            links.append(f'<a href="{href}">{label}</a>')
    return '<div class="axes-nav">' + "\n".join(links) + "</div>"


def homepage(library: dict, all_items: list[dict]) -> str:
    """Render the wiki homepage."""
    collection_name = library.get("collection_name", "alexandria")
    total = len([b for b in all_items if b.get("status", "active") != "removed"])

    section_counts: dict[str, int] = {}
    type_counts: dict[str, int] = {}
    form_counts: dict[str, int] = {"physical": 0, "digital": 0}
    for item in all_items:
        if item.get("status", "active") == "removed":
            continue
        section_counts[item.get("section", "unsorted")] = section_counts.get(item.get("section", "unsorted"), 0) + 1
        type_counts[item.get("book_type", "unknown")] = type_counts.get(item.get("book_type", "unknown"), 0) + 1
        form_counts[item.get("form", "digital")] = form_counts.get(item.get("form", "digital"), 0) + 1

    n_sections = len(section_counts)
    n_types = len(type_counts)

    # Recent additions (most recent 10, excluding removed)
    active = [b for b in all_items if b.get("status", "active") != "removed"]
    recent = sorted(active, key=lambda b: b.get("date_added", ""), reverse=True)[:10]
    if recent:
        recent_cards = "\n".join(
            _item_card(b, f"items/{b['slug']}.html") for b in recent
        )
        recent_section = f"""<h2>Recent additions</h2>
<div class="index-grid">
{recent_cards}
</div>"""
    else:
        recent_section = """<h2>Recent additions</h2>
<p>No items yet. Use <code>/coll</code> or <code>/coll-physical</code>, <code>/coll-digital</code>, or <code>/coll-scout</code> to add your first item.</p>"""

    stats = f"{total} item{'s' if total != 1 else ''} · {n_sections} section{'s' if n_sections != 1 else ''} · {form_counts.get('physical', 0)} physical · {form_counts.get('digital', 0)} digital &ensp;|&ensp; <a href=\"collection-journal/index.html\">Journal</a>"

    body = f"""{_axes_nav()}

{recent_section}
"""
    return _page(collection_name, "", body, STYLESHEET_REL, stats=stats)


def by_section_index(library: dict, items_by_section: dict[str, list[dict]]) -> str:
    """Render the by-section index: list of sections with counts."""
    collection_name = library.get("collection_name", "alexandria")
    rows = []
    for section in sorted(items_by_section.keys()):
        items = [b for b in items_by_section[section] if b.get("status", "active") != "removed"]
        count = len(items)
        # Section filename is the section name itself, safe-ified by the generator
        section_slug = section.replace("/", "-").replace(" ", "-").lower()
        rows.append(
            f'<tr><td><a href="{section_slug}.html">{escape(section)}</a></td><td>{count}</td></tr>'
        )
    table = (
        '<table><thead><tr><th>Section</th><th>Items</th></tr></thead><tbody>'
        + "\n".join(rows)
        + "</tbody></table>"
    )

    body = f"""{_axes_nav("by-section", from_subdir=True)}

{table}
"""
    breadcrumb = f'<a href="../index.html">{escape(collection_name)}</a> / By section'
    return _page(f"{collection_name} — by section", breadcrumb, body, "../" + STYLESHEET_REL, from_subdir=True)


def section_page(section: str, items: list[dict], collection_name: str = "collection") -> str:
    """Render a single section page: all items in that section."""
    if not items:
        body_main = '<p>No items in this section yet.</p>'
    else:
        cards = "\n".join(_item_card(b, f"../items/{b['slug']}.html") for b in items)
        body_main = f'<div class="index-grid">\n{cards}\n</div>'

    body = f"""<p><a href="index.html">← All sections</a></p>

{body_main}
"""
    breadcrumb = f'<a href="../index.html">{escape(collection_name)}</a> / <a href="index.html">By section</a> / ' + escape(section)
    return _page(f"Section: {section}", breadcrumb, body, "../" + STYLESHEET_REL, from_subdir=True)


def by_date_index(library: dict, all_items: list[dict]) -> str:
    """Render the by-date index: items newest first, grouped by year-month."""
    collection_name = library.get("collection_name", "alexandria")
    # Group by YYYY-MM
    groups: dict[str, list[dict]] = {}
    for item in all_items:
        date_added = item.get("date_added", "")
        if not date_added or len(date_added) < 7:
            group_key = "unknown"
        else:
            group_key = date_added[:7]
        groups.setdefault(group_key, []).append(item)

    sections = []
    for group_key in sorted(groups.keys(), reverse=True):
        items = sorted(groups[group_key], key=lambda b: b.get("date_added", ""), reverse=True)
        cards = "\n".join(_item_card(b, f"../items/{b['slug']}.html") for b in items)
        label = escape(group_key) if group_key != "unknown" else "Date unknown"
        sections.append(
            f'<div class="section-group"><h2>{label}</h2><div class="index-grid">\n{cards}\n</div></div>'
        )

    body = f"""{_axes_nav("by-date", from_subdir=True)}

{''.join(sections) if sections else '<p>No items to display.</p>'}
"""
    breadcrumb = f'<a href="../index.html">{escape(collection_name)}</a> / By date'
    return _page(f"{collection_name} — by date", breadcrumb, body, "../" + STYLESHEET_REL, from_subdir=True)


def by_type_index(library: dict, all_items: list[dict]) -> str:
    """Render the by-type index: books grouped by book_type."""
    collection_name = library.get("collection_name", "alexandria")
    groups: dict[str, list[dict]] = {}
    for item in all_items:
        groups.setdefault(item.get("book_type", "unknown"), []).append(item)

    sections = []
    for type_name in sorted(groups.keys()):
        items = sorted(groups[type_name], key=lambda b: b.get("title", "").lower())
        cards = "\n".join(_item_card(b, f"../items/{b['slug']}.html") for b in items)
        count = len([b for b in items if b.get("status", "active") != "removed"])
        sections.append(
            f'<div class="section-group"><h2>{escape(type_name)} <small>({count})</small></h2>'
            f'<div class="index-grid">\n{cards}\n</div></div>'
        )

    body = f"""{_axes_nav("by-type", from_subdir=True)}

{''.join(sections) if sections else '<p>No items to display.</p>'}
"""
    breadcrumb = f'<a href="../index.html">{escape(collection_name)}</a> / By type'
    return _page(f"{collection_name} — by type", breadcrumb, body, "../" + STYLESHEET_REL, from_subdir=True)


def by_media_type_index(library: dict, all_items: list[dict]) -> str:
    """Render the by-media-type index: grouped by content_type then format."""
    collection_name = library.get("collection_name", "alexandria")
    # Two-level grouping: content_type -> format -> [items]
    content_groups: dict[str, dict[str, list[dict]]] = {}
    for item in all_items:
        media_type = item.get("media_type", "")
        if ":" in media_type:
            content_type, fmt = media_type.split(":", 1)
        else:
            content_type, fmt = "other", media_type or "unknown"
        content_groups.setdefault(content_type, {}).setdefault(fmt, []).append(item)

    sections = []
    for content_type in sorted(content_groups.keys()):
        format_groups = content_groups[content_type]
        total_for_type = sum(
            len([b for b in items if b.get("status", "active") != "removed"])
            for items in format_groups.values()
        )
        if total_for_type == 0:
            continue
        format_sections = []
        for fmt in sorted(format_groups.keys()):
            items = sorted(format_groups[fmt], key=lambda b: b.get("title", "").lower())
            cards = "\n".join(_item_card(b, f"../items/{b['slug']}.html") for b in items)
            active_count = len([b for b in items if b.get("status", "active") != "removed"])
            if active_count == 0:
                continue
            format_sections.append(
                f'<h3>{escape(fmt)} <small>({active_count})</small></h3>'
                f'<div class="index-grid">\n{cards}\n</div>'
            )
        sections.append(
            f'<div class="section-group"><h2>{escape(content_type)}</h2>'
            + "\n".join(format_sections)
            + "</div>"
        )

    body = f"""{_axes_nav("by-media-type", from_subdir=True)}

{''.join(sections) if sections else '<p>No items to display.</p>'}
"""
    breadcrumb = f'<a href="../index.html">{escape(collection_name)}</a> / By media type'
    return _page(f"{collection_name} — by media type", breadcrumb, body, "../" + STYLESHEET_REL, from_subdir=True)


def topic_placeholder(library: dict) -> str:
    """Pass 2 scaffolding: placeholder for the topic index page."""
    collection_name = library.get("collection_name", "alexandria")
    body = """<p>Topic pages will appear here once narrative layer generation is enabled.</p>

<p>The narrative layer uses an LLM to extract topics from your items and generate
cross-references between them. It's an optional enhancement — the wiki works fully
without it.</p>

<p><a href="../index.html">← Back</a></p>
"""
    breadcrumb = f'<a href="../index.html">{escape(collection_name)}</a> / By topic'
    return _page(f"{collection_name} — by topic", breadcrumb, body, "../" + STYLESHEET_REL, from_subdir=True)


def collection_journal(library: dict, entries: list[dict]) -> str:
    """Render the collection journal as a timeline page.

    Each entry is a dict with:
      - date: str (YYYY-MM-DD)
      - time: str (HH:MM)
      - accomplished: str (the headline)
      - full_html: str (the full checkpoint content rendered as HTML)
    """
    collection_name = library.get("collection_name", "alexandria")

    if not entries:
        body = f"""{_axes_nav("collection-journal", from_subdir=True)}

<p>No journal entries yet. After adding items or making changes to your collection,
run <code>/coll-notes</code> to record what was done. You can also add personal
notes about your collection — thoughts, plans, or anything you want to remember.</p>

<p>Journal entries appear here as a timeline, grouped by month.</p>
"""
        breadcrumb = f'<a href="../index.html">{escape(collection_name)}</a> / Journal'
        return _page(f"{collection_name} — journal", breadcrumb, body, "../" + STYLESHEET_REL, from_subdir=True)

    # Group entries by year-month (newest first)
    months: dict[str, list[dict]] = {}
    for entry in entries:
        date = entry.get("date", "")
        if len(date) >= 7:
            month_key = date[:7]
        else:
            month_key = "undated"
        months.setdefault(month_key, []).append(entry)

    month_sections = []
    for month_key in sorted(months.keys(), reverse=True):
        month_entries = sorted(months[month_key], key=lambda e: e.get("date", "") + e.get("time", ""), reverse=True)

        entry_cards = []
        for entry in month_entries:
            date = escape(entry.get("date", ""))
            time = escape(entry.get("time", ""))
            accomplished = escape(entry.get("accomplished", ""))
            full_html = entry.get("full_html", "")

            timestamp = f"{date}"
            if time:
                timestamp += f" at {time}"

            headline = accomplished if accomplished else "Checkpoint"

            entry_cards.append(f"""<article class="journal-entry">
<div class="journal-date">{timestamp}</div>
<h3 class="journal-headline">{headline}</h3>
<div class="journal-detail">
{full_html}
</div>
</article>""")

        label = escape(month_key) if month_key != "undated" else "Undated"
        month_sections.append(
            f'<div class="section-group"><h2>{label}</h2>\n'
            + "\n".join(entry_cards)
            + "\n</div>"
        )

    body = f"""{_axes_nav("collection-journal", from_subdir=True)}

<p class="journal-intro">A timeline of your collection — what was added, changed, and decided,
in chronological order. Run <code>/coll-notes</code> to add entries with personal details.</p>

{''.join(month_sections)}
"""
    breadcrumb = f'<a href="../index.html">{escape(collection_name)}</a> / Journal'
    return _page(f"{collection_name} — journal", breadcrumb, body, "../" + STYLESHEET_REL, from_subdir=True)


def search_page(library: dict, all_items: list[dict]) -> str:
    """Render the search page with inline JS for filtering and highlighting.

    Fully client-side: no external dependencies, no CDN, no network requests.
    The JS filters items to show only matches and highlights matching text.
    Case-insensitive partial matching. Works over file://.
    """
    collection_name = library.get("collection_name", "alexandria")

    # Build the flat listing — every active item with all searchable fields visible
    item_entries = []
    active = [b for b in all_items if b.get("status", "active") != "removed"]
    for item in sorted(active, key=lambda b: b.get("title", "").lower()):
        title = escape(item.get("title", "Untitled"))
        author = escape(item.get("author", ""))
        description = escape(item.get("description", ""))
        section = escape(item.get("section", ""))
        media_type = escape(item.get("media_type", ""))
        slug = item.get("slug", "")
        user_notes = escape(item.get("user_notes", ""))

        parts = [f'<div class="search-item" data-searchable>']
        parts.append(f'<div class="search-title"><a href="../items/{slug}.html">{title}</a></div>')
        if author:
            parts.append(f'<div class="search-meta">{author}</div>')
        if description:
            parts.append(f'<div class="search-desc">{description}</div>')
        detail_parts = []
        if section:
            detail_parts.append(section)
        if media_type:
            detail_parts.append(media_type)
        if detail_parts:
            parts.append(f'<div class="search-detail">{" · ".join(detail_parts)}</div>')
        if user_notes:
            parts.append(f'<div class="search-notes">{user_notes}</div>')
        parts.append('</div>')
        item_entries.append("\n".join(parts))

    listing = "\n".join(item_entries) if item_entries else "<p>No items in the collection yet.</p>"

    # The search script: ~80 lines inline, zero dependencies
    search_script = """
<script>
(function() {
  var input = document.getElementById('search-input');
  var prompt = document.getElementById('search-prompt');
  var items = document.querySelectorAll('[data-searchable]');
  var listing = document.querySelector('.search-listing');

  // Read query from URL on page load
  var params = new URLSearchParams(location.search);
  var initial = params.get('q') || '';
  if (initial) {
    input.value = initial;
    runSearch(initial);
  }

  // Live search on input (no need to press Enter after first load)
  input.addEventListener('input', function() {
    runSearch(input.value);
  });

  // Prevent form submission reload when typing — search live instead
  input.closest('form').addEventListener('submit', function(e) {
    e.preventDefault();
    runSearch(input.value);
    // Update URL without reload so bookmarking works
    var url = new URL(location);
    if (input.value) url.searchParams.set('q', input.value);
    else url.searchParams.delete('q');
    history.replaceState(null, '', url);
  });

  function runSearch(query) {
    var q = query.trim().toLowerCase();

    // Clear previous highlights
    items.forEach(function(el) {
      el.style.display = '';
      // Restore original text (strip <mark> tags)
      el.querySelectorAll('mark').forEach(function(m) {
        m.replaceWith(m.textContent);
      });
    });

    if (!q) {
      prompt.style.display = 'none';
      return;
    }

    var shown = 0;
    var terms = q.split(/\\s+/).filter(function(t) { return t.length > 0; });

    items.forEach(function(el) {
      var text = el.textContent.toLowerCase();
      var match = terms.every(function(t) { return text.indexOf(t) !== -1; });

      if (match) {
        el.style.display = '';
        shown++;
        // Highlight matching terms in text nodes
        highlightTerms(el, terms);
      } else {
        el.style.display = 'none';
      }
    });

    prompt.style.display = 'block';
    if (shown === 0) {
      prompt.innerHTML = 'No matches for <strong>' + esc(query) + '</strong>';
    } else {
      prompt.innerHTML = shown + ' match' + (shown === 1 ? '' : 'es') + ' for <strong>' + esc(query) + '</strong>';
    }
  }

  function highlightTerms(root, terms) {
    var walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null);
    var nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);

    nodes.forEach(function(node) {
      var html = node.textContent;
      terms.forEach(function(term) {
        var re = new RegExp('(' + escRegex(term) + ')', 'gi');
        html = html.replace(re, '<mark>$1</mark>');
      });
      if (html !== node.textContent) {
        var span = document.createElement('span');
        span.innerHTML = html;
        node.replaceWith(span);
      }
    });
  }

  function esc(s) { return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
  function escRegex(s) { return s.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&'); }
})();
</script>"""

    body = f"""{_axes_nav("search", from_subdir=True)}

<form class="search-form" action="index.html" method="get">
<input type="text" name="q" placeholder="Search the collection…" id="search-input" autocomplete="off">
</form>

<div id="search-prompt" class="search-prompt" style="display:none;"></div>

<div class="search-listing">
{listing}
</div>

{search_script}
"""
    breadcrumb = f'<a href="../index.html">{escape(collection_name)}</a> / Search'
    return _page(f"{collection_name} — search", breadcrumb, body, "../" + STYLESHEET_REL, from_subdir=True)


def item_page(item: dict, readme_html: str, readme_truncated: bool, item_notes: list[dict] | None = None, collection_name: str = "collection") -> str:
    """Render a single item page.

    `readme_html` is the item's README content rendered to HTML (may be empty).
    `readme_truncated` is True if the content was truncated to the word limit.
    `item_notes` is a list of note dicts from the notes/ directory, each with:
      filename, title, html, is_pdf.
    """
    title = escape(item.get("title", "Untitled"))
    description = escape(item.get("description", ""))
    author = item.get("author")
    user_notes = item.get("user_notes")
    book_type = escape(item.get("book_type", "unknown"))
    form = escape(item.get("form", ""))
    media_type = escape(item.get("media_type", ""))
    section = escape(item.get("section", ""))
    date_added = escape(item.get("date_added", ""))
    status = item.get("status", "active")
    settled = bool(item.get("settled", False))
    slug = escape(item.get("slug", ""))
    path = item.get("path", "")

    # Metadata block
    metadata_rows = [
        f"<dt>Book type</dt><dd>{book_type}</dd>",
        f"<dt>Form</dt><dd>{form}</dd>",
    ]
    if media_type:
        metadata_rows.append(f"<dt>Media type</dt><dd>{media_type}</dd>")
    metadata_rows.append(f"<dt>Section</dt><dd><a href=\"../by-section/{section.lower().replace(' ', '-')}.html\">{section}</a></dd>")
    metadata_rows.append(f"<dt>Date added</dt><dd>{date_added}</dd>")
    if author:
        metadata_rows.insert(0, f"<dt>Author</dt><dd>{escape(author)}</dd>")

    if item.get("book_type") == "scout":
        if settled:
            settled_at = escape(item.get("settled_at", ""))
            metadata_rows.append(f"<dt>Scout status</dt><dd>Settled (static reference)</dd>")
            if settled_at:
                metadata_rows.append(f"<dt>Settled at</dt><dd>{settled_at}</dd>")
        else:
            metadata_rows.append(f"<dt>Scout status</dt><dd>Live (updates via discovery)</dd>")

    if status == "removed":
        removed_at = escape(item.get("removed_at", ""))
        removed_reason = escape(item.get("removed_reason", ""))
        metadata_rows.append(f"<dt>Status</dt><dd><strong>Removed</strong></dd>")
        if removed_at:
            metadata_rows.append(f"<dt>Removed at</dt><dd>{removed_at}</dd>")
        if removed_reason:
            metadata_rows.append(f"<dt>Removal reason</dt><dd>{removed_reason}</dd>")

    metadata_block = f"""<div class="item-metadata"><dl>
{''.join(metadata_rows)}
</dl></div>"""

    # Content block
    if status == "removed":
        content_block = """<div class="removed-notice">
<strong>Resource removed.</strong> This item is kept in the catalog as a historical
record. The original content is no longer in the collection.
</div>"""
    elif item.get("book_type") == "scout" and not settled:
        # Live scout: thin catalog entry linking to the scout's own presentation
        content_block = f"""<div class="item-content">
<p><a href="../../{path}/README.md">Open the scout's full content</a> in a markdown viewer,
or <a href="../../{path}/">browse the scout directory</a>.</p>
</div>"""
    elif readme_html:
        truncation_note = ""
        if readme_truncated:
            truncation_note = f'<p><em>Content truncated. <a href="../../{path}/README.md">See full README</a>.</em></p>'
        content_block = f'<div class="item-content">\n{readme_html}\n{truncation_note}\n</div>'
    else:
        content_block = f"""<div class="item-content">
<p>Content is preserved in the item's directory. <a href="../../{path}/">Browse the item directory</a>.</p>
</div>"""

    description_html = f'<p class="description">{description}</p>' if description else ""
    user_notes_html = f'<blockquote class="user-notes"><p>{escape(user_notes)}</p></blockquote>' if user_notes else ""

    # Render notes from notes/ directory
    notes_section = ""
    if item_notes:
        note_blocks = []
        for note in (item_notes or []):
            if note["is_pdf"]:
                note_blocks.append(
                    f'<div class="note-entry">'
                    f'<h3>{escape(note["title"])}</h3>'
                    f'<p>📄 <a href="../../{path}/notes/{note["filename"]}">Open as PDF</a></p>'
                    f'</div>'
                )
            else:
                note_blocks.append(
                    f'<div class="note-entry">'
                    f'<h3>{escape(note["title"])}</h3>'
                    f'{note["html"]}'
                    f'</div>'
                )
        notes_section = f"""<div class="item-notes">
<h2>Notes</h2>
{''.join(note_blocks)}
</div>"""

    body = f"""{description_html}

{user_notes_html}

{metadata_block}

{content_block}

{notes_section}

<p><a href="../index.html">← Back</a></p>
"""

    breadcrumb = f'<a href="../index.html">{escape(collection_name)}</a> / <a href="../by-section/{section.lower().replace(" ", "-")}.html">{section}</a> / {title}'
    return _page(title, breadcrumb, body, "../" + STYLESHEET_REL, from_subdir=True)
